# -*- coding: utf-8 -*-
"""Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXCBZgX42ZFcMyn_745HpLNdwHFr0Myu
"""

pip install pandas numpy matplotlib seaborn requests kaggle mysql-connector-python

pip install kaggle

import os

os.environ['KAGGLE_USERNAME'] = "your_kaggle_username"
os.environ['KAGGLE_KEY'] = "your_kaggle_api_key"

os.system("kaggle datasets download -d shivamb/netflix-shows")

import zipfile

with zipfile.ZipFile("netflix-shows.zip", 'r') as zip_ref:
    zip_ref.extractall("netflix_data")

import pandas as pd

df = pd.read_csv("netflix_data/netflix_titles.csv")

print(df.head())
print(df.info())

df.shape
df.columns
df.describe()

df.isnull().sum()

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')

df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')

df.drop_duplicates(inplace=True)

df['year_added'] = df['date_added'].dt.year

df['month_added'] = df['date_added'].dt.month

df['content_age'] = 2025 - df['release_year']

df['type'].value_counts()

df['country'].value_counts().head(10)

df['release_year'].value_counts().sort_index()

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(data=df, x='type')

plt.title("Movies vs TV Shows on Netflix")
plt.show()

top_countries = df['country'].value_counts().head(10)

top_countries.plot(kind='bar')

plt.title("Top Countries Producing Netflix Content")
plt.xlabel("Country")
plt.ylabel("Number of Titles")

plt.show()

genres = df['listed_in'].str.split(', ', expand=True)

genre_counts = genres.stack().value_counts()

print(genre_counts.head(10))

df.to_csv("cleaned_netflix_data.csv", index=False)

df.to_excel("cleaned_netflix_data.xlsx", index=False)

df.to_csv("netflix_dashboard_data.csv", index=False)

year_data = df.groupby('release_year').size()

year_data.plot()

plt.title("Content Growth on Netflix")
plt.xlabel("Year")
plt.ylabel("Number of Titles")

plt.show()

trend = df.groupby(['release_year','type']).size().unstack()

trend.plot()

plt.title("Movies vs TV Shows Trend")
plt.show()

df.describe().to_csv("netflix_summary_statistics.csv")